myclub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('rankinglist/', include('rankinglist.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('static/favicon.ico'))),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rankinglist/urls.py
from django.urls import path, include, re_path

from . import views
from django.contrib.auth import views as auth_views
from .routers import ReadOnlyRouter
from .viewsets import RankinglistViewSet

router = ReadOnlyRouter()
router.register('rankinglist', RankinglistViewSet)


urlpatterns = [
    path('api/', include(router.urls)),
    path('', views.index, name='index'),
    path('club/<int:club_id>', views.clubmain, name='clubmain'),
    path('club/<int:club_id>/player/<int:player_id>/history', views.playerhistory, name='player_history'),
    path('club/<int:club_id>/rl/<int:rankinglist_id>/stats', views.rankingliststats, name='rankinglist_stats'),
    # path('club/<int:club_id>/match/history', views.matcheshistory, name='matcheshistory'),
    path("signup", views.signup, name='signup'),
    # re_path(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('login', auth_views.LoginView.as_view(template_name='rankinglist/login.html'),name="login"),
    path('logout', auth_views.LogoutView.as_view(template_name='rankinglist/logout.html'),name="logout"),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('user/<int:pk>', views.UserUpdateView.as_view(), name='user_update'), 

]

rankinglist/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

import logging
logger = logging.getLogger('rankinglist')

class Club(models.Model):
    name = models.CharField(max_length=255)
    # path = models.CharField(max_length=255)
    #TODO  logo + address + google map

    def __str__(self):
        return self.name

class Rankinglist(models.Model):
    name = models.CharField(max_length=255)
    active = models.BooleanField(default=True)
    club = models.ForeignKey(Club, on_delete=models.CASCADE,null=True)
    admin = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Rangliste"
        verbose_name_plural = "Ranglisten"

class Player(models.Model):    
    # if deleted set ranking and matches to a "deleted" user
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    club = models.ForeignKey(Club, on_delete=models.CASCADE, null=True)
    leistungsklasse = models.IntegerField(default=0)
    email_confirmed = models.BooleanField(default=False)

    @receiver(post_save, sender=User,dispatch_uid="player_create")
    def create_save_user_player(sender, instance, created, **kwargs):
        if created:
            Player.objects.create(user=instance)

    @receiver(post_save, sender=User,dispatch_uid="player_save")
    def save_user_player(sender, instance, **kwargs):
        instance.player.save()

    def __str__(self):
        return "%s %s" % (self.user.first_name, self.user.last_name)

    def nameshort(self):
        return "%s %s. (LK%s)" % (self.user.first_name, self.user.last_name[:1],self.leistungsklasse)
    
    class Meta:    
        verbose_name = "Spieler"
        verbose_name_plural = "Spieler"

class Ranking(models.Model):
    position = models.IntegerField(default=0)
    rankinglist = models.ForeignKey(Rankinglist, on_delete=models.CASCADE, related_name="rankings")
    player = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return "%s: %s %s" % (self.rankinglist, self.position, self.player)

    class Meta:
        ordering = ["position"]
        verbose_name = "Position"
        verbose_name_plural = "Positionen"
        constraints = [
            models.UniqueConstraint(fields=['position', 'rankinglist','player'], name='uniqueranking')
        ]

        
class Match(models.Model):
    GEPLANT='geplant'
    GESPIELT='gespielt'
    ABGEBROCHEN='abgebrochen'
    MATCHSTATUS_CHOICES = (
    (GEPLANT,'geplant'),
    (GESPIELT,'gespielt'),
    (ABGEBROCHEN,'abgebrochen'),
    )

    rankinglist = models.ForeignKey(Rankinglist, on_delete=models.CASCADE,verbose_name='Rangliste')
    playerone = models.ForeignKey(User, related_name='playerone', on_delete=models.CASCADE,verbose_name='Spieler 1 (Sieger)')
    playertwo = models.ForeignKey(User, related_name='playertwo', on_delete=models.CASCADE,verbose_name='Spieler 2')
    playedat = models.DateTimeField(verbose_name='Spieldatum')
    set1playerone = models.IntegerField(default=0,verbose_name='Satz1 - Spieler 1',validators=[MaxValueValidator(7), MinValueValidator(0)])
    set1playertwo = models.IntegerField(default=0,verbose_name='Satz1 - Spieler 2',validators=[MaxValueValidator(7), MinValueValidator(0)])
    set2playerone = models.IntegerField(default=0,verbose_name='Satz2 - Spieler 1',validators=[MaxValueValidator(7), MinValueValidator(0)])
    set2playertwo = models.IntegerField(default=0,verbose_name='Satz2 - Spieler 2',validators=[MaxValueValidator(7), MinValueValidator(0)])
    set3playerone = models.IntegerField(default=0,verbose_name='Satz3 - Spieler 1',validators=[MaxValueValidator(10), MinValueValidator(0)])
    set3playertwo = models.IntegerField(default=0,verbose_name='Satz3 - Spieler 2',validators=[MaxValueValidator(10), MinValueValidator(0)])
    status = models.CharField(max_length=20, choices=MATCHSTATUS_CHOICES, default=GEPLANT)

    
    def __str__(self):
        return "%s: %s vs %s - %s" % (self.rankinglist,self.playerone,self.playertwo,self.playedat)

    def set1(self):
        return "%s : %s" % (self.set1playerone,self.set1playertwo)
    
    def set2(self):
        return "%s : %s" % (self.set2playerone,self.set2playertwo)

    def set3(self):
        if self.set3playerone != 0 and self.set3playertwo != 0:
            return "%s : %s" % (self.set2playerone,self.set2playertwo)
        else:
            return ""
    class Meta:
         verbose_name = "Spiel"
         verbose_name_plural = "Spiele"


@receiver(post_delete,sender=Ranking, dispatch_uid='ranking_delete')
def ranking_delete(sender, **kwargs):
    ranking = kwargs['instance']
    logger.debug("in ranking delete signal")
    rankings_after = Ranking.objects.filter(rankinglist=ranking.rankinglist,position__gt=ranking.position)
    ranking_pos = ranking.position
    for r in rankings_after:
        r.position = ranking_pos
        r.save()
        ranking_pos += 1

rankinglist/forms.py
from django import forms
from .choices import *
from .models import Rankinglist, Match, Ranking, Club
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Div
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from captcha.fields import ReCaptchaField

class MatchesHistoryForm(forms.Form):
    year = forms.ChoiceField(choices = YEAR_CHOICES,label='Jahr')

#class RankinglistSelForm(forms.Form):
#    def __init__(self, *args, **kwargs):
#        super(RankinglistSelForm, self).__init__(*args, **kwargs)
#        self.helper = FormHelper()
#        self.helper.form_show_labels = False
        #self.fields['rl'].label = ''
#        self.helper.layout = Layout(
#            Field('rl',css_class="form-control form-control-sm"),            
#        )
    
#    rankinglists = Rankinglist.objects.filter(active=True).order_by('name')
#    rl = forms.ChoiceField(label="Rangliste",choices=[(r.id, r.name) for r in rankinglists])

class MatchAdminForm(forms.ModelForm):
    class Meta:
        model = Match
        exclude = ('update_user','updatedate','activatedate','activate_user')

    def clean(self):
        cleaned_data = self.cleaned_data

        # check whether ranking exists
        rankinglist = cleaned_data.get('rankinglist')        
        playerone = cleaned_data.get('playerone')
        playertwo = cleaned_data.get('playertwo')

        ranking_playerone = Ranking.objects.filter(rankinglist=rankinglist,player=playerone).first()
        ranking_playertwo = Ranking.objects.filter(rankinglist=rankinglist,player=playertwo).first()
        
        if ranking_playerone is None: 
            raise forms.ValidationError('Das Spiel kann nicht gespeichert werden. Spieler 1 hat noch keine Ranglistenposition')

        if ranking_playertwo is None:
            raise forms.ValidationError('Das Spiel kann nicht gespeichert werden. Spieler 2 hat noch keine Ranglistenposition')

        return cleaned_data

class SignUpForm(UserCreationForm):
    club = forms.ModelChoiceField(queryset=Club.objects.all(), empty_label=None)
    leistungsklasse = forms.IntegerField( max_value=23, min_value=1,required=False)
    captcha = ReCaptchaField()

    class Meta:
        model = User
        fields = ('club','first_name', 'last_name','leistungsklasse', 'username', 'email', 'password1', 'password2', )

rankinglist/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from operator import itemgetter
from django.contrib.auth.models import User
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.template.loader import render_to_string
from django.utils.encoding import force_text
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse

from .models import Rankinglist, Match, Player, Ranking, Club
from .forms import MatchesHistoryForm, SignUpForm
from .tokens import account_activation_token


import logging
logger = logging.getLogger('rankinglist')

# Create your views here.

def index(request):
    clubs = Club.objects.all()
    context = {        
        'clubs': clubs,
    }
    # logger.debug('in index')
    return render(request, 'rankinglist/index.html', context)

def clubmain(request,club_id):
    club = get_object_or_404(Club,pk=club_id)
    request.session['club_name'] = club.name
    request.session['club_id'] = club.id
    rankinglists = Rankinglist.objects.filter(club=club ,active=True)
    matches = Match.objects.filter(rankinglist__in=rankinglists).exclude(status=Match.GEPLANT).order_by('-playedat') # [:10] first 10
    matches_planned=Match.objects.filter(rankinglist__in=rankinglists,status=Match.GEPLANT).order_by('playedat')
    context = {        
        'rankinglists': rankinglists,
        'matches': matches,
        'matches_planned': matches_planned,
        'club': club,
    }
    return render(request, 'rankinglist/clubmain.html', context)

def playerhistory(request,club_id,player_id):
    player = get_object_or_404(User, pk=player_id)
    club = get_object_or_404(Club,pk=club_id)
    matcheswon = Match.objects.filter(playerone=player).exclude(status=Match.GEPLANT)
    matcheslost = Match.objects.filter(playertwo=player).exclude(status=Match.GEPLANT)
    context = {        
        'player': player,
        'matcheswon': matcheswon,
        'matcheslost': matcheslost,        
        'matcheswonCount': len(matcheswon),
        'matcheslostCount': len(matcheslost),     
        'club': club,   
    }
    return render(request, 'rankinglist/playerhistory.html', context)

def rankingliststats(request,club_id,rankinglist_id):
    club = get_object_or_404(Club,pk=club_id)
    rankinglist = get_object_or_404(Rankinglist, pk=rankinglist_id)
    playerList = []
    for ranking in rankinglist.rankings.all():
        countWon = Match.objects.filter(rankinglist=rankinglist,playerone=ranking.player).exclude(status=Match.GEPLANT).count()
        countLost= Match.objects.filter(rankinglist=rankinglist,playertwo=ranking.player).exclude(status=Match.GEPLANT).count()
        playerList.append((ranking.player,countWon+countLost))

    # todo count matches in rankinglist by player in playerList
    context = {        
        'rankinglist': rankinglist,
        'players': sorted(playerList,key=itemgetter(1),reverse=True),
        'club': club,
    }
    return render(request, 'rankinglist/rankingliststats.html', context)

#def matcheshistory(request):
#    if( request.method == 'POST'):
#        form = MatchesHistoryForm(request.POST)
#        if (form.is_valid()):
#            year = form.cleaned_data['year']
#            logger.debug("Year %s in matches history" %(year))
            # TODO in 2021 - load by year
#            return render(request, 'rankinglist/matcheshistory.html', {'form': form, 'matches': []})
#    else:
#        form = MatchesHistoryForm()
#    m = Match.objects.all().exclude(status=Match.GEPLANT).order_by('-playedat') # TODO in 2021 - load by year
#    return render(request, 'rankinglist/matcheshistory.html', {'form': form, 'matches': m})

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.player.leistungsklasse = form.cleaned_data.get('leistungsklasse')
            user.player.club = form.cleaned_data.get('club')
            user.save()
            current_site = get_current_site(request)
            subject = 'Bestätige deine Registrierung bei mytennisclub.online'
            message = render_to_string('rankinglist/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            messages.add_message(
                request, messages.INFO, "Die Registrierung war erfolgreich. Bitte bestätigen sie die Emailadresse in ihrem Postfach."
            )
            return redirect('index')
    else:
        form = SignUpForm()
    return render(request, 'rankinglist/signup.html', {'form': form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        # user.is_active = True
        user.player.email_confirmed = True
        user.save()
        login(request, user)
        messages.add_message(
                request, messages.INFO, "Die Emailbestätigung war erfolgreich."
            )
        return redirect('index')
    else:
        return render(request, 'rankinglist/account_activation_invalid.html')

def account_activation_sent(request):
    return render(request, 'rankinglist/account_activation_sent.html')

class UserUpdateView(LoginRequiredMixin, UpdateView):
    #form_class = UserChangeForm
    model = User    
    template_name = 'rankinglist/user_update.html'
    fields = ["first_name","last_name","email"]
    

    def get_success_url(self):
        # return reverse("users_detail", kwargs={"username": self.request.user.username})
        return reverse("index")

    #def get_object(self):
    #    return User.objects.get(pk=self.request.user.pk)
        #return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, "Profil wurde erfolgreich aktualisiert"
        )
        return super().form_valid(form)

rankinglist/templates/rankinglist/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Bitte bestätige deine Mailadresse mit Klick auf den Link

https://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

rankinglist/templates/rankinglist/account_activation_invalid.html
{% extends "rankinglist/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<p>Bei der Aktivierung ist was schief gegangen. Vielleicht wurde der Aktivierungslink schon einmal benutzt</p>

{% endblock %}

rankinglist/templates/rankinglist/base.html
<!DOCTYPE html>
<html class="h-100">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>mytennisclub</title>

    {% load static %}
    <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
        <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      main > .container {
        padding: 70px 15px 0;
      }
    </style>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


 <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    </head>
    <body class="d-flex flex-column h-100">

    <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
      <a class="navbar-brand" href="{% url 'index' %}">MTC</a>     
      {% if user.is_authenticated and 'club_id' in request.session %}
      <a class="navbar-brand" href="{% url 'clubmain' club_id=request.session.club_id %}"><small>{{user.first_name}}@{{ request.session.club_name }}</small></a>      
      {% elif 'club_id' in request.session %}
      <a class="navbar-brand" href="{% url 'clubmain' club_id=request.session.club_id %}"><small>{{ request.session.club_name }}</small></a>
      {%endif%}
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse w-100 order-3 dual-collapse2" id="navbarsExample09">

        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}            
            <a class="nav-link" href="{% url 'user_update' user.id %}">Profil</a>            
            <a class="nav-link" href="{% url 'logout' %}">Ausloggen</a>
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          {% else %}
            <a class="nav-link" href="{% url 'signup' %}">Registrieren</a>            
            <a class="nav-link" href="{% url 'login' %}">Einloggen</a>    
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>        
          {% endif %}   
      </ul>  
            
      </div> 
    </nav>
</header>

    <main role="main" class="flex-shrink-0">

    <div class="container">
      {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
          {% endfor %}
      {% endif %}
    
        {% block content %}{% endblock %}
     </div>

     <script>
      setTimeout(function(){
        if ($('#msg').length > 0) {
          $('#msg').remove();
        }
      }, 10000)
    </script> 
    </main><!-- /.container -->

    <footer class="footer mt-auto py-3 bg-dark text-white-50">      
      <div class="container text-center">
        <a href="http://www.mytennisclub.online" target="_blank">&copy Copyright 2020: mytennisclub.online</a>
        Impressum | AGB | Datenschutzrichtlinie | <a href="https://github.com/puredriver/myclub/blob/master/README.md#v030" target="_blank" >Version 0.3.0</a> 
      </div>
    </footer>

    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/cookie-bar/cookiebar-latest.min.js?always=1"></script>

    </body>
</html>

rankinglist/templates/rankinglist/index.html
{% extends "rankinglist/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">

  <div class="list-group pt-2">

    {% for c in clubs %}
          <a href="{% url 'clubmain' club_id=c.id  %}" class="list-group-item list-group-item-action">Startseite {{c.name}}</a>        
       
    {% endfor %}  
 
  </div>

</div>

{% endblock %}

rankinglist/templates/rankinglist/login.html
{% extends "rankinglist/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

    <h5>Einloggen</h5>

    {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    
    {% if next %}
        {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
        {% else %}
        <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}
    
    <form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Einloggen</button>
    <input type="hidden" name="next" value="{{ next }}">
    </form>
    
    {# Assumes you setup the password_reset view in your URLconf #}
    <p><a href="{%url 'password_reset'%}">Passwort vergessen?</a></p>

{% endblock %}

rankinglist/templates/rankinglist/logout.html
{% extends "rankinglist/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

    <h5>Erfolgreich ausgeloggt!</h5>
    
  <a href="{% url 'login' %}">Wieder einloggen?</a>

{% endblock %}

rankinglist/templates/rankinglist/match_form.html
{% extends "rankinglist/base.html" %}

{% load crispy_forms_tags %}


{% block content %}

<h5>Spiel</h5>

<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}

    <button class="btn btn-primary" type="submit">Speichern</button>
    <a href="{% url 'index' %}" class="btn btn-secondary">Abbrechen</a>
</form>
    


{% endblock %}

rankinglist/templates/rankinglist/matcheshistory.html
{% extends "rankinglist/base.html" %}

{% load crispy_forms_tags %}

{% block content %}


<a class="btn btn-primary btn-sm float-right" href="{% url 'clubmain' club.id %}" role="button">Zurück</a>

<h5>Spielearchiv</h5>

<form action="" method="post" name="yearForm">
    {% csrf_token %}
    {{ form|crispy }}   
</form>

<table class="table table-sm">
  <thead>
      <tr>
      <th>Datum</th>
      <th>Rangliste</th>
          <th>Spieler 1 <br>(Sieger)</th>
          <th>Spieler 2</th>
          <th>Ergebnis</th>
          
      </tr>
  </thead>
<tbody>
  {% for m in matches %}
      <tr>
          <td>{{ m.playedat }}</td>
          <td>{{ m.rankinglist }}</td>
          <td>{{ m.playerone.player.nameshort }}</td>
          <td>{{ m.playertwo.player.nameshort }}</td>
          <td>{{ m.set1playerone }}:{{ m.set1playertwo }}                 
          {{ m.set2playerone }}:{{ m.set2playertwo }}

          {% if m.set3playerone != 0 and m.set3playertwo != 0 %}
              {{ m.set3playerone }}:{{ m.set3playertwo }}
          {% endif %}  
        </td>
         
      </tr>
  {% empty %}
      <tr>
          <td colspan="8">Keine Spiele</td>
      </tr>
  {% endfor %}
  </tbody>
</table> 

<script>
    $('#id_year').on('change', function(e){
            this.form.submit()
        });
    </script>


{% endblock %}

rankinglist/templates/rankinglist/matchnewwizard.html
{% extends "rankinglist/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head %}
{{ wizard.form.media }}
{% endblock %}

{% block content %}

<h5>Eingabe des Spielergebnis</h5>

<p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
<form action="" method="post">{% csrf_token %}
<table>
{{ wizard.management_form }}
{% if wizard.form.forms %}
    {{ wizard.form.management_form }}
    {% for form in wizard.form.forms %}
        {{ form|crispy }}
    {% endfor %}
{% else %}
    {{ wizard.form |crispy}}
{% endif %}
</table>
{% if wizard.steps.prev %}
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">{% trans "first step" %}</button>
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">{% trans "prev step" %}</button>
{% endif %}
<input type="submit" value="{% trans "submit" %}"/>
</form>

{% endblock %}

rankinglist/templates/rankinglist/rankingliststats.html
{% extends "rankinglist/base.html" %}

{% block content %}

<a class="btn btn-primary btn-sm float-right" href="{% url 'clubmain' club_id=club.id %}" role="button">Zurück</a>

    <h5>Statistiken für {{ rankinglist.name }}</h5>
    <h6>Die meisten Spiele</h6>
    <table class="table table-sm">
        <thead>
            <tr>
            
            <th scope="col">Name</th>            
            <th scope="col">Anzahl Spiele</th>    
        </tr>
        </thead>
        <tbody>
            {% for entry in players %}
            <tr>
            <td scope="row">{{entry.0.player.nameshort}}</td>
            <td>{{entry.1}}</td> 
            </tr>
            {% endfor %}
        <tbody>
    </table> 


{% endblock %}